# Generated by Django 3.1.1 on 2020-11-13 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200, unique=True)),
                ('user_first_name', models.CharField(max_length=50)),
                ('user_last_name', models.CharField(max_length=50)),
                ('user_street_add', models.CharField(max_length=150)),
                ('user_city_add', models.CharField(max_length=150)),
                ('user_state_add', models.CharField(max_length=30)),
                ('user_zip', models.CharField(max_length=6)),
                ('user_email', models.CharField(max_length=50)),
                ('user_phone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('issue_name', models.CharField(max_length=200)),
            ],
        ),
    ]
