# Generated by Django 3.1.1 on 2020-11-13 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0001_initial'),
    ]

    operations = [
    ]
