# Generated by Django 3.1.1 on 2020-11-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0002_auto_20201112_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issue_text',
            field=models.CharField(default='DefaultIssueName', max_length=3000),
            preserve_default=False,
        ),
    ]
