# Generated by Django 3.1.1 on 2020-11-20 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0003_issue_issue_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('issue_name', models.CharField(max_length=200)),
                ('issue_text', models.CharField(max_length=3000)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
