# Generated by Django 3.1.1 on 2020-11-20 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0004_usertemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='user_id',
            field=models.CharField(default='admin', max_length=200),
        ),
    ]
